# Generated by Django 2.2 on 2020-04-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ad_name',
            field=models.URLField(),
        ),
    ]
