# Generated by Django 2.2 on 2020-04-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200410_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ad_name',
            new_name='ad_url',
        ),
    ]
