# Generated by Django 2.2 on 2020-04-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200410_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='flickr_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='googleplus_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
