# Generated by Django 2.2 on 2020-04-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200410_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='sologan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
