# Generated by Django 2.2 on 2020-04-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200407_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.CharField(default='Dhaka', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default='Badda', max_length=200),
            preserve_default=False,
        ),
    ]
